// Class automatically generated by Dev-C++ New Class wizard

#ifndef BYTECODE_H
#define BYTECODE_H

#include "jtype.h"


class ByteCode {

	public:
		/*! The first instruction */
        static const u1 BYTECODE_FIRST  = 0;

		/*! The Last instruction */
		static const u1 BYTECODE_LAST	= 209;
        
		/*! Instructions */
        static const u1 NOP             = 0;
        static const u1 ACONST_NULL     = 1;
        static const u1 ICONST_M1       = 2;
        static const u1 ICONST_0        = 3;
        static const u1 ICONST_1        = 4;
        static const u1 ICONST_2        = 5;
        static const u1 ICONST_3        = 6;
        static const u1 ICONST_4        = 7;
        static const u1 ICONST_5        = 8;
        static const u1 LCONST_0        = 9;
        static const u1 LCONST_1        = 10;
        static const u1 FCONST_0        = 11;
        static const u1 FCONST_1        = 12;
        static const u1 FCONST_2        = 13;
        static const u1 DCONST_0        = 14;
        static const u1 DCONST_1        = 15;
        static const u1 BIPUSH          = 16;
        static const u1 SIPUSH          = 17;
        static const u1 LDC1            = 18;
        static const u1 LDC2            = 19;
        static const u1 LDC2W           = 20;
        static const u1 ILOAD           = 21;
        static const u1 LLOAD           = 22;
        static const u1 FLOAD           = 23;
        static const u1 DLOAD           = 24;
        static const u1 ALOAD           = 25;
        static const u1 ILOAD_0         = 26;
        static const u1 ILOAD_1         = 27;
        static const u1 ILOAD_2         = 28;
        static const u1 ILOAD_3         = 29;
        static const u1 LLOAD_0         = 30;
        static const u1 LLOAD_1         = 31;
        static const u1 LLOAD_2         = 32;
        static const u1 LLOAD_3         = 33;
        static const u1 FLOAD_0         = 34;
        static const u1 FLOAD_1         = 35;
        static const u1 FLOAD_2         = 36;
        static const u1 FLOAD_3         = 37;
        static const u1 DLOAD_0         = 38;
        static const u1 DLOAD_1         = 39;
        static const u1 DLOAD_2         = 40;
        static const u1 DLOAD_3         = 41;
        static const u1 ALOAD_0         = 42;
        static const u1 ALOAD_1         = 43;
        static const u1 ALOAD_2         = 44;
        static const u1 ALOAD_3         = 45;
        static const u1 IALOAD          = 46;
        static const u1 LALOAD          = 47;
        static const u1 FALOAD          = 48;
        static const u1 DALOAD          = 49;
        static const u1 AALOAD          = 50;
        static const u1 BALOAD          = 51;
        static const u1 CALOAD          = 52;
        static const u1 SALOAD          = 53;
        static const u1 ISTORE          = 54;
        static const u1 LSTORE          = 55;
        static const u1 FSTORE          = 56;
        static const u1 DSTORE          = 57;
        static const u1 ASTORE          = 58;
        static const u1 ISTORE_0        = 59;
        static const u1 ISTORE_1        = 60;
        static const u1 ISTORE_2        = 61;
        static const u1 ISOTRE_3        = 62;
        static const u1 LSTORE_0        = 63;
        static const u1 LSTORE_1        = 64;
        static const u1 LSTORE_2        = 65;
		static const u1 LSTORE_3		= 66;
		static const u1 FSTORE_0		= 67;
		static const u1 FSTORE_1		= 68;
		static const u1 FSTORE_2		= 69;
		static const u1 FSTORE_3		= 70;
		static const u1 DSTORE_0		= 71;
		static const u1 DSTORE_1		= 72;
		static const u1 DSTORE_2		= 73;
		static const u1 DSTORE_3		= 74;
		static const u1 ASTORE_0		= 75;
		static const u1 ASTORE_1		= 76;
		static const u1 ASTORE_2		= 77;
		static const u1 ASTORE_3		= 78;
		static const u1 IASTORE			= 79;
		static const u1 LASTORE			= 80;
		static const u1 FASTORE			= 81;
		static const u1 DASTORE			= 82;
		static const u1 AASTORE			= 83;
		static const u1 BASTORE			= 84;
		static const u1 CASTORE			= 85;
		static const u1 SASTORE			= 86;
		static const u1 POP				= 87;
		static const u1 POP2			= 88;
		static const u1 DUP				= 89;
		static const u1 DUP_X1			= 90;
		static const u1 DUP_X2			= 91;
		static const u1 DUP2			= 92;
		static const u1 DUP2_X1			= 93;
		static const u1 DUP2_X2			= 94;
		static const u1 SWAP			= 95;
		static const u1 IADD			= 96;
		static const u1 LADD			= 97;
		static const u1 FADD			= 98;
		static const u1 DADD            = 99;
		static const u1 ISUB            = 100;
		static const u1 LSUB            = 101;
		static const u1 FSUB            = 102;
		static const u1 DSUB            = 103;
		static const u1 IMUL            = 104;
		static const u1 LMUL            = 105;
		static const u1 FMUL            = 106;
		static const u1 DMUL            = 107;
		static const u1 IDIV            = 108;
		static const u1 LDIV            = 109;
		static const u1 FDIV            = 110;
		static const u1 DDIV            = 111;
		static const u1 IREM            = 112;
		static const u1 LREM            = 113;
		static const u1 FREM            = 114;
		static const u1 DREM            = 115;
		static const u1 INEG            = 116;
		static const u1 LNEG            = 117;
		static const u1 FNEG            = 118;
		static const u1 DNEG            = 119;
		static const u1 ISHL            = 120;
		static const u1 LSHL            = 121;
		static const u1 ISHR            = 122;
		static const u1 LSHR            = 123;
		static const u1 IUSHR           = 124;
		static const u1 LUSHR           = 125;
		static const u1 IAND            = 126;
		static const u1 LAND            = 127;
		static const u1 IOR             = 128;
		static const u1 LOR             = 129;
		static const u1 IXOR            = 130;
		static const u1 LXOR            = 131;
		static const u1 IINC            = 132;
		static const u1 I2L             = 133;
		static const u1 I2F             = 134;
		static const u1 I2D             = 135;
		static const u1 L2I             = 136;
		static const u1 L2F             = 137;
		static const u1 L2D             = 138;
		static const u1 F2I             = 139;
		static const u1 F2L             = 140;
		static const u1 F2D             = 141;
		static const u1 D2I             = 142;
		static const u1 D2L             = 143;
		static const u1 D2F             = 144;
		static const u1 INT2BYTE        = 145;
		static const u1 INT2CHAR        = 146;
		static const u1 INT2SHORT       = 147;
		static const u1 LCMP            = 148;
		static const u1 FCMPL           = 149;
		static const u1 FCMPG           = 150;
		static const u1 DCMPL           = 151;
		static const u1 DCMPG           = 152;
		static const u1 IFEQ            = 153;
		static const u1 IFNE            = 154;
		static const u1 IFLT            = 155;
		static const u1 IFGE            = 156;
		static const u1 IFGT            = 156;
		static const u1 IFLE            = 158;
		static const u1 IF_ICMPEQ       = 159;
		static const u1 IF_ICMPNE       = 160;
		static const u1 IF_ICMPLT       = 161;
		static const u1 IF_ICMPGE       = 162;
		static const u1 IF_ICMPGT       = 163;
		static const u1 IF_ICMPLE       = 164;
		static const u1 IF_ACMPEQ       = 165;
		static const u1 IF_ACMPNE       = 166;
		static const u1 GOTO            = 167;
		static const u1 JSR             = 168;
		static const u1 RET             = 169;
		static const u1 TABLESWITCH     = 170;
		static const u1 LOOKUPSWITCH    = 171;
		static const u1 IRETURN         = 172;
		static const u1 LRETURN         = 173;
		static const u1 FRETURN         = 174;
		static const u1 DRETURN         = 175;
		static const u1 ARETURN         = 176;
		static const u1 RETURN          = 177;
		static const u1 GETSTATIC       = 178;
		static const u1 PUTSTATIC       = 179;
		static const u1 GETFIELD        = 180;
		static const u1 PUTFIELD        = 181;
		static const u1 INVOKEVIRTUAL   = 182;
		static const u1 INVOKENONVIRTUAL= 183;
		static const u1 INVOKESTATIC    = 184;
		static const u1 INVOKEINTERFACE = 185;
		static const u1 NEW             = 187;
		static const u1 NEWARRAY        = 188;
		static const u1 ANEWARRAY       = 189;
		static const u1 ARRAYLENGTH     = 190;
		static const u1 ATHROW          = 191;
		static const u1 CHECKCAST       = 192;
		static const u1 INSTANCEOF      = 193;
		static const u1 MONITORENTER    = 194;
		static const u1 MONITOREXIT     = 195;
		static const u1 WIDE            = 196;
		static const u1 MULTIANEWARRAY  = 197;
		static const u1 IFNULL          = 198;
		static const u1 IFNONNULL       = 199;
		static const u1 GOTO_W          = 200;
		static const u1 JSR_2           = 201;            //SOME QUESTION HERE
		static const u1 BREADPOINT      = 202;
		static const u1 RET_W           = 209;

        //TODO: Add more instructions here.
        
		/*! class constructor */
		ByteCode();

		/*! class destructor */
		~ByteCode();

		/*! Get readable instruction */
		static const char* getInstructionText(u1 instruction);
};

/*!
	\class ByteCode
	Class ByteCode enum java instructions and provides a method 
		to convert byte code instruction into readable instruction.
*/

#endif // BYTECODE_H

