// Class automatically generated by Dev-C++ New Class wizard

#include "constantlong.h" // class's header file
#include "toolkit.h"

// class constructor
ConstantLong::ConstantLong()
{
	// insert your code here
	setTag(Constant::LONG);
}

// class destructor
ConstantLong::~ConstantLong()
{
	// insert your code here
}

void ConstantLong::customSerialize(JBuffer* buf, UINT& pos) {
	/*
    	u1 tag;
    	u4 high_bytes;
    	u4 low_bytes;
	*/
	ToolKit::memSetU4(buf->getBuffer(), getHighByte(), buf->getSize(), pos);
	ToolKit::memSetU4(buf->getBuffer(), getLowByte(), buf->getSize(), pos);
}
