// Class automatically generated by Dev-C++ New Class wizard

#include "constantnameandtype.h" // class's header file
#include "toolkit.h"

// class constructor
ConstantNameAndType::ConstantNameAndType()
{
	// insert your code here
	setTag(Constant::NAME_AND_TYPE);
}

// class destructor
ConstantNameAndType::~ConstantNameAndType()
{
	// insert your code here
}

void ConstantNameAndType::customSerialize(JBuffer* buf, UINT& pos) {
	/*
		CONSTANT_NameAndType_info {
    		u1 tag;
    		u2 name_index;
    		u2 descriptor_index;
		}
	*/
	ToolKit::memSetU2(buf->getBuffer(), getNameIndex(), buf->getSize(), pos);
	ToolKit::memSetU2(buf->getBuffer(), getSignatureIndex(), buf->getSize(), pos);
}


