// Class automatically generated by Dev-C++ New Class wizard

#include "constantunicode.h" // class's header file
#include <assert.h>
#include <string.h>
#include "toolkit.h"

// class constructor
ConstantUnicode::ConstantUnicode(u2 strLength)
{
	// insert your code here
	assert(strLength > 0);
	length = strLength;
	bytes = new u2[length + 1];
	memset(bytes,0,sizeof(u2)*length);
	setTag(Constant::UNICODE);
}

// class destructor
ConstantUnicode::~ConstantUnicode()
{
	// insert your code here
	if(bytes) {
	   delete[] bytes;
    }
}

void ConstantUnicode::customSerialize(JBuffer* buf, UINT& pos) {
	ToolKit::memSetU2(buf->getBuffer(), length, buf->getSize(), pos);
	ToolKit::memSetUnicodeString(buf->getBuffer(), getBytes(), length, buf->getSize(), pos);
}
