// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTINT_H
#define CONSTINT_H

#include "constant.h" // inheriting class's header file

class ConstantInt : public Constant
{
    protected:
        INT value;

		void customSerialize(JBuffer* buf, UINT& pos);

	public:
		/*! Constructor */
		ConstantInt();

		/*! Destructor */
		~ConstantInt();
		
		/*! Get value */
		inline INT getValue() { return value;};
		/*! Set Value */
		inline void setValue(INT x) { value = x; };
};

/*!
	\class ConstantInt
	Class ConstantInt represent integer constant in java class file.
	See Java Virtual Machine Specification for more detail about java class file.
*/

#endif // CONSTINT_H

