// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTANTFLOAT_H
#define CONSTANTFLOAT_H

#include "constant.h" // inheriting class's header file

// No description
class ConstantFloat : public Constant
{
    protected:
        float value;

		void customSerialize(JBuffer* buf, UINT& pos);

	public:
		/*! Constructor */
		ConstantFloat();

		/*! Destructor */
		virtual ~ConstantFloat();

		/*! Get value */
		inline float getValue() { return value;};
		/*! Set value */

		inline void setValue(float x) { value = x ; };
};

/*!
	\class ConstantFloat
	Class ConstantFloat represent float constant in java class file.
	See Java Virtual Machine Specification for more detail about java class file.
*/

#endif // CONSTANTFLOAT_H

