// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTANTUNICODE_H
#define CONSTANTUNICODE_H

#include "constant.h" // inheriting class's header file

// No description
class ConstantUnicode : public Constant
{
    protected:
        u2 length;
        
		u2*bytes;

		void customSerialize(JBuffer* buf, UINT& pos);

	public:
		/*! class constructor */
		ConstantUnicode(u2 strLength);

		/*! class destructor */
		~ConstantUnicode();
		
		/*! Get unicode string */
		inline u2*getBytes() { return bytes;};
};

/*!
	\class ConstantUnicode
	Class ConstantUnicode represent unicode string constant in java class file.
	See Java Virtual Machine Specification for more detail about java class file.
*/

#endif // CONSTANTUNICODE_H

