// Class automatically generated by Dev-C++ New Class wizard

#include "constclass.h" // class's header file
#include "toolkit.h"

// class constructor
ConstantClass::ConstantClass()
{
	// insert your code here
	setTag(Constant::CLASS);
}

// class destructor
ConstantClass::~ConstantClass()
{
	// insert your code here
}

void ConstantClass::customSerialize(JBuffer* buf, UINT& pos) {
	ToolKit::memSetU2(buf->getBuffer(), getNameIndex(), buf->getSize(), pos);
}
