// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTANTSTRING_H
#define CONSTANTSTRING_H

#include "constant.h" // inheriting class's header file

class ConstantString : public Constant
{
    protected:
        u2 stringIndex;

		void customSerialize(JBuffer* buf, UINT& pos);

	public:
		/*! class constructor */
		ConstantString();

		/*! class destructor */
		~ConstantString();
		
		/*! Get string index */
		inline u2 getStringIndex() { return stringIndex;};

		/*! Set string index */
		inline void setStringIndex(u2 x) { stringIndex = x ;};
};

/*!
	\class ConstantString
	Class ConstantString represent String constant in java class file.
	See Java Virtual Machine Specification for more detail about java class file.
*/

#endif // CONSTANTSTRING_H

