// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTANTLONG_H
#define CONSTANTLONG_H

#include "constant.h" // inheriting class's header file

class ConstantLong : public Constant
{   
    protected:
		/*! High byte */
        u4 highBytes;

		/*! Low byte */
        u4 lowBytes;


		void customSerialize(JBuffer* buf, UINT& pos);

	public:
		/*! Constructor */
		ConstantLong();
		
		/*! Destructor */
		~ConstantLong();
		
		/*! Get high byte of long */
		inline u4 getHighByte() { return highBytes; };
		
		/*! Get Low byte of long */
		inline void setHighByte(u4 x) { highBytes = x ;};
        
		/*! Get Low byte of low */
        inline u4 getLowByte() { return lowBytes;};
        
		/*! Set low byte of low */
		inline void setLowByte(u4 x) { lowBytes = x ;};
        
};

/*!
	\class ConstantLong
	Class ConstantLong represent Long constant in java class file.
	See Java Virtual Machine Specification for more detail about java class file.
*/

#endif // CONSTANTLONG_H

