// Class automatically generated by Dev-C++ New Class wizard

#include "constantutf8.h" // class's header file
#include <string.h>
#include "toolkit.h"

// class constructor
ConstantUtf8::ConstantUtf8(u2 stringLength)
{
	// insert your code here
	length = stringLength;
	bytes = new u1[length + 1];
	memset(bytes,0,(length + 1)*sizeof(u1));
	setTag(Constant::UTF8);
}

// class destructor
ConstantUtf8::~ConstantUtf8()
{
	// insert your code here
	if(bytes) {
	   delete[] bytes;
	   bytes = NULL;
    }
}

u1* ConstantUtf8::getBytes()
{
    return bytes;
}

void ConstantUtf8::customSerialize(JBuffer* buf, UINT& pos) {
	ToolKit::memSetU2(buf->getBuffer(), length, buf->getSize(), pos);
	ToolKit::memSetUtfString(buf->getBuffer(), bytes, length, buf->getSize(), pos);
}
