// Class automatically generated by Dev-C++ New Class wizard

#include "constint.h" // class's header file
#include "toolkit.h"

// class constructor
ConstantInt::ConstantInt()
{
	// insert your code here
	setTag(Constant::INTEGER);
}

// class destructor
ConstantInt::~ConstantInt()
{
	// insert your code here
}

void ConstantInt::customSerialize(JBuffer* buf, UINT& pos) {
	ToolKit::memSetU4(buf->getBuffer(), (u4)getValue(), buf->getSize(), pos);
}
