// Class automatically generated by Dev-C++ New Class wizard

#ifndef CONSTANTCLASS_H
#define CONSTANTCLASS_H

#include "jtype.h" // inheriting class's header file
#include "jbuffer.h"


// No description
class Constant {

    protected:
        u1 tag;

		virtual void customSerialize(JBuffer* buf, UINT& pos);

	public:
		/*! UTF8 constant */
        static const int UTF8           = 1;

		/*! Unicode constant */
        static const int UNICODE        = 2;

		/*! Integer constant */
        static const int INTEGER        = 3;

		/*! Float constant */
        static const int FLOAT          = 4;

		/*! Long constant */
        static const int LONG           = 5;

		/*! Double constant */
        static const int DOUBLE         = 6;

		/*! Class Constant */
        static const int CLASS          = 7;

		/*! String Constant */
        static const int STRING         = 8;

		/*! Reference of Field */
        static const int FIELD_REF       = 9;

		/*! Reference of Method */
        static const int METHOD_REF      = 10;

		/*! Reference of method of interface */
        static const int INTF_METHOD_REF = 11;

		/*! Name and Type */
        static const int NAME_AND_TYPE   = 12;

		/*! class constructor */
		Constant();

		/*! class destructor */
		virtual ~Constant();

		/*! Get Tag of Constant */
		inline u1 getTag() { return tag;};

		/*! Set Tag of Constant */
		inline void setTag(u1 x) { tag = x; };

		void serialize(JBuffer* buf, UINT& pos);

                //virtual int serialize(u1* buffer, unsigned long length, unsigned long* currentPos);
};

/*!
    \class Constant
    Class Constant represents Constant Pool element.
	Please see Java Virtual Machine for detail of Constant Pool.
*/

#endif // CONSTANTCLASS_H

