// Class automatically generated by Dev-C++ New Class wizard

#include "constant.h" // class's header file
#include "toolkit.h"

// class constructor
Constant::Constant()
{
	// insert your code here
	setTag(0);
}

// class destructor
Constant::~Constant()
{
	// insert your code here
}

void Constant::serialize(JBuffer* buf, UINT& pos) {
	/*
		cp_info {
    		u1 tag;
    		u1 info[];
		}
	*/
	
	ToolKit::memSetU1(buf->getBuffer(), this->tag, buf->getSize(), pos);
	customSerialize(buf, pos);
}

void Constant::customSerialize(JBuffer* buf, UINT& pos) {
}

