// Class automatically generated by Dev-C++ New Class wizard

#include "constantref.h" // class's header file
#include "toolkit.h"

// class constructor
ConstantRef::ConstantRef()
{
	// insert your code here
}

// class destructor
ConstantRef::~ConstantRef()
{
	// insert your code here
}

void ConstantRef::customSerialize(JBuffer* buf, UINT& pos) {
	ToolKit::memSetU2(buf->getBuffer(), classIndex, buf->getSize(), pos);
	ToolKit::memSetU2(buf->getBuffer(), nameAndTypeIndex, buf->getSize(), pos);
}
