// Class automatically generated by Dev-C++ New Class wizard

#ifndef GENERICATTRIBUTE_H
#define GENERICATTRIBUTE_H

#include "jobject.h" // inheriting class's header file
#include "jbuffer.h"


class GenericAttribute : public JObject
{
    protected:
        u2 attributeName;
        u4 attributeLength;
        u1*info;

	public:
	
	    //TODO: Add flag here
      
		/*! Constructor */
		GenericAttribute();
		/*! Destructor  */
		~GenericAttribute();
		
		/*! Get name index of attribute */
		inline u2 getAttributeName() { return attributeName; };
		/*! Set name inde xof attribute */
		inline void setAttributeName(u2 _name) { attributeName = _name; };
		
		/*! Get attribute Length */
		inline u4 getAttributeLength() { return attributeLength; };
		/*! Set attribute length */
		inline void setAttributeLength(u4 _length) { attributeLength = _length; };
		
		/*! Get content of attribute */
		inline u1* getInfo() { return info;};
		
		/*! Initialization of content */
		void initInfo(u4 infoLength);
		
		void serialize(JBuffer* buf, UINT& pos);
};

/*!
	\class GenericAttribute
	GenericAttribute represents attribute of java class.
	Java Virtual Machine Specification may tell you more about java class file format.
*/

#endif // GENERICATTRIBUTE_H

