// Class automatically generated by Dev-C++ New Class wizard

#include "genericattribute.h" // class's header file
#include "toolkit.h"
#include <string.h>

// class constructor
GenericAttribute::GenericAttribute()
{
	// insert your code here
	info = (u1*)0;
}

// class destructor
GenericAttribute::~GenericAttribute()
{
	// insert your code here
	if(info) {
	   delete[] info;
    }
}

void GenericAttribute::initInfo(u4 infoLength)
{
    if(info) {
        delete[] info;
    }
    info = new u1[infoLength];
    memset(info,0,sizeof(u1)*infoLength);
}

void GenericAttribute::serialize(JBuffer* buf, UINT& pos) {
	/*
		attribute_info {
    		u2 attribute_name_index;
    		u4 attribute_length;
    		u1 info[attribute_length];
		}
	*/
	ToolKit::memSetU2(buf->getBuffer(), attributeName, buf->getSize(), pos);
	ToolKit::memSetU4(buf->getBuffer(), attributeLength, buf->getSize(), pos);
	ToolKit::memSetU1Array(buf->getBuffer(), info, attributeLength, buf->getSize(), pos);
}