// Class automatically generated by Dev-C++ New Class wizard

#ifndef JOBJECT_H
#define JOBJECT_H

//#ifndef JASM_DEBUG
//#define JASM_DEBUG
//#endif

#include "jtype.h"

// No description
class JObject
{
	public:
		// class constructor
		JObject();
		// class destructor
		~JObject();
};

/*!
	\class JObject
	Common base class.
*/

#endif // JOBJECT_H

