// Class automatically generated by Dev-C++ New Class wizard

#include "jobject.h" // class's header file

// class constructor
JObject::JObject()
{
	// insert your code here
}

// class destructor
JObject::~JObject()
{
	// insert your code here
}

