// Class automatically generated by Dev-C++ New Class wizard

#ifndef METHODINFO_H
#define METHODINFO_H

#include "attributecontainer.h" // inheriting class's header file


class MethodInfo : public AttributeContainer
{
    typedef GenericAttribute* AttributeElement;

    public:
      static const u2 PUBLIC  = 0x0001;
      static const u2 PRIVATE = 0x0002;
      static const u2 PROTECTED = 0x0004;
      static const u2 STATIC  = 0x0008;
      static const u2 FINAL   = 0x0010;
      static const u2 SYNCHRONIZED  = 0x0020;
      static const u2 NATIVE  = 0x0100;
      static const u2 ABSTRACT  = 0x0400;
      static const u2 STRICT  = 0x0800;


    protected:
        u2 accessFlags;
        u2 nameIndex;
        u2 signatureIndex;
        u2 attributesCount;
        AttributeElement*attributes;

        void initAttributes();

    public:
		// class constructor
		MethodInfo();
		// class destructor
		virtual ~MethodInfo();

		/*! Set attribute of method,parameter pos is position of attribute */
        virtual void setAttribute(GenericAttribute* attribute,u2 pos);
		/*! Get attribute of method */
        virtual GenericAttribute* getAttribute(u2 pos);

		/*! Get Access Flags */
        inline u2 getAccessFlags() { return accessFlags;};
		/*! Set Access Flags */
        inline void setAccessFlags(u2 _accessFlags) { accessFlags = _accessFlags;};

		/*! Get Name index */
        inline u2 getNameIndex() { return nameIndex;};
		/*! Set Name index */
        inline void setNameIndex(u2 _name) { nameIndex = _name;};

		/*! Get signature index */
        inline u2 getSignatureIndex() { return signatureIndex;};
		/*! Set Signature index */
        inline void setSignatureIndex(u2 _signature) { signatureIndex = _signature;};

		/*! Get attributes count */
        inline u2 getAttributesCount() { return attributesCount;};
		/*! Set attributes count */
        void setAttributesCount(u2 _attributesCount);

		void serialize(JBuffer* buf, UINT& pos);
};

/*!
	\class MethodInfo
	Class MethodInfo represent java method.
	Please see Java Virtual Machine Specificatio for more detail.
*/

#endif // METHODINFO_H

